### ISSUE TITLE
Dependabot Omnibus 0.119.5 throwing "undefined method `homepage_url'"

### ISSUE THREAD

**Issue by BobbyMcWho** [dependabot/dependabot-core#2542]
**Package manager/ecosystem**  
> ruby:bundler  

**Manifest contents prior to update**  
Gemfile  
```ruby
gem 'loofah', '2.3.0'
gem 'hashie', '~> 3'
gem 'rails', '~> 5.2.2'
gem 'sprockets', '< 4.0.0'
```
Gemfile.lock  
```ruby
GEM
  remote: https://gems.covermymeds.com/
  specs:
    actioncable (5.2.2)
      actionpack (= 5.2.2)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.2)
      actionpack (= 5.2.2)
      actionview (= 5.2.2)
      activejob (= 5.2.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.2)
      actionview (= 5.2.2)
      activesupport (= 5.2.2)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.2)
      activesupport (= 5.2.2)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.2.2)
      activesupport (= 5.2.2)
      globalid (>= 0.3.6)
    activemodel (5.2.2)
      activesupport (= 5.2.2)
    activerecord (5.2.2)
      activemodel (= 5.2.2)
      activesupport (= 5.2.2)
      arel (>= 9.0)
    activestorage (5.2.2)
      actionpack (= 5.2.2)
      activerecord (= 5.2.2)
      marcel (~> 0.3.1)
    activesupport (5.2.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (9.0.0)
    builder (3.2.4)
    concurrent-ruby (1.1.6)
    crass (1.0.5)
    erubi (1.9.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    hashie (3.6.0)
    i18n (1.8.3)
      concurrent-ruby (~> 1.0)
    loofah (2.3.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    method_source (1.0.0)
    mimemagic (0.3.5)
    mini_mime (1.0.2)
    mini_portile2 (2.4.0)
    minitest (5.14.1)
    nio4r (2.5.2)
    nokogiri (1.10.5)
      mini_portile2 (~> 2.4.0)
    rack (2.2.2)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (5.2.2)
      actioncable (= 5.2.2)
      actionmailer (= 5.2.2)
      actionpack (= 5.2.2)
      actionview (= 5.2.2)
      activejob (= 5.2.2)
      activemodel (= 5.2.2)
      activerecord (= 5.2.2)
      activestorage (= 5.2.2)
      activesupport (= 5.2.2)
      bundler (>= 1.3.0)
      railties (= 5.2.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (5.2.2)
      actionpack (= 5.2.2)
      activesupport (= 5.2.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rake (13.0.1)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (1.0.1)
    thread_safe (0.3.6)
    tzinfo (1.2.7)
      thread_safe (~> 0.1)
    websocket-driver (0.7.2)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  hashie (~> 3)
  loofah (= 2.3.0)
  rails (~> 5.2.2)
  sprockets (< 4.0.0)

BUNDLED WITH
   1.17.3
```
**Updated dependency**  
> I believe this failed while parsing websocket-extensions.   

**What you expected to see, versus what you actually saw**  
Expected the script to create a PR, instead got an  error:  
```
/var/lib/gems/2.6.0/gems/dependabot-common-0.119.5/lib/dependabot/pull_request_creator/message_builder.rb:266:in `block in dependency_links': undefined method `homepage_url' for #<Dependabot::PullRequestCreator::MessageBuilder:0x000055aaddd3d848> (NoMethodError)

	from /var/lib/gems/2.6.0/gems/dependabot-common-0.119.5/lib/dependabot/pull_request_creator/message_builder.rb:263:in `map'

	from /var/lib/gems/2.6.0/gems/dependabot-common-0.119.5/lib/dependabot/pull_request_creator/message_builder.rb:263:in `dependency_links'

	from /var/lib/****/builds/workspace/my_dependabot-ci_master/dependabot_monkey_patch.rb:59:in `multidependency_intro'

	from /var/lib/gems/2.6.0/gems/dependabot-common-0.119.5/lib/dependabot/pull_request_creator/message_builder.rb:180:in `version_commit_message_intro'

	from /var/lib/gems/2.6.0/gems/dependabot-common-0.119.5/lib/dependabot/pull_request_creator/message_builder.rb:119:in `commit_message_intro'

	from /var/lib/gems/2.6.0/gems/dependabot-common-0.119.5/lib/dependabot/pull_request_creator/message_builder.rb:53:in `commit_message'

	from /var/lib/gems/2.6.0/gems/dependabot-common-0.119.5/lib/dependabot/pull_request_creator.rb:102:in `github_creator'

	from /var/lib/gems/2.6.0/gems/dependabot-common-0.119.5/lib/dependabot/pull_request_creator.rb:73:in `create'

	from ./update-script.rb:207:in `<main>'
```

I have tested and this does not occur on 0.119.4, only 0.119.5.

**Comment by thepwagner** [comment]
Likely https://github.com/dependabot/dependabot-core/pull/2539

**Comment by brrygrdn** [comment]
Yeah, looks like an issue introduced in #2539

**Comment by brrygrdn** [comment]
This issue should be fixed in v0.119.6, apologies for the breakages 🙇🏻‍♂️

**Comment by BobbyMcWho** [comment]
Thanks for the quick fix!
